export const API='API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SET_ALL_ANNONCES= 'SET_ALL_ANNONCES';
export const ADD_ANNONCE= 'ADD_ANNONCE';
export const SEARCH_ANNONCE= 'SEARCH_ANNONCE';
export const REMOVE_ANNONCE= 'REMOVE_ANNONCE';
export const UPDATE_ANNONCE= 'UPDATE_ANNONCE';
export const GET_ANNONCE_BY_MARQUE= 'GET_ANNONCE_BY_MARQUE';
